routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', 'Site\HomeController@index')->name('site');
Route::post('home.save', 'Site\HomeController@save')->name('home.save');

Route::prefix('admin')->group(function(){
    Route::get('/', 'Admin\ConteudoController@index')->name('admin');

    Route::get('register', 'Admin\Auth\RegisterController@index')->name('register');
    Route::post('register', 'Admin\Auth\RegisterController@register');

    Route::get('login', 'Admin\Auth\LoginController@index')->name('login');
    Route::post('login', 'Admin\Auth\LoginController@authenticate');

    Route::post('logout', 'Admin\Auth\LoginController@logout')->name('logout');


    Route::get('conteudos', 'Admin\ConteudoController@index')->name('conteudos');
    Route::put('conteudos.save', 'Admin\ConteudoController@save')->name('conteudos.save');

    Route::resource('characters', 'Admin\CharacterController');
});

app/Character.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Character extends Model
{
    //
}

app/Http/Controllers/Admin/CharacterController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Validator;
use App\Character;
use Illuminate\Support\Facades\Auth;

class CharacterController extends Controller
{
    public function __construct(){
        $this->middleware('auth');
    }

    public function index(){
        $characters = Character::paginate(2);

        return view('admin.characters.index', ['characters' => $characters]);
    }

    public function create(){
        return view('admin.characters.create');
    }

    public function store(Request $request){
        $data = $request->only([
            'descricao',
        ]);

        $validator = $this->validator($data);

        if($validator->fails()){
            return redirect()->route('characters.create')->withErrors($validator)->withInput();
        }

        //upload image
        $request->validate(['imagem' => 'image|mimes:jpeg,jpg,png']);

        if ($request->file('imagem')) {
            $destinationPath = 'uploads/images/characters/';
            $ext = $request->imagem->extension();
            $bgImage = time() . "." . $ext;
            $request->imagem->move($destinationPath, $bgImage);
            $data['imagem'] =$destinationPath.$bgImage;
         }

         $newCharacter = new Character();
         $newCharacter->descricao = $data['descricao'];
         $newCharacter->imagem = (isset($data['imagem']) && !empty($data['imagem']) ? $data['imagem'] : '');
         $newCharacter->save();
         

        return redirect()->route('characters.index')->with('warning', 'Personagem adicionado com sucesso!');
    }

    public function edit($id){
        $character = Character::find($id);

        if($character){
            return view('admin.characters.edit', ['character' => $character]);
        }

        return redirect()->route('characters.index');

        
    }

    public function update(Request $request, $id){

        $character = Character::find($id);

        if($character){
            $data = $request->only([
                'descricao',
            ]);
    
            $validator = $this->validator($data);
    
            if($validator->fails()){
                return redirect()->route('characters.edit', ['character' => $id])->withErrors($validator);
            }
    
            //upload image
            $request->validate(['imagem' => 'image|mimes:jpeg,jpg,png']);
    
            if ($request->file('imagem')) {
                $destinationPath = 'uploads/images/characters/';
                $ext = $request->imagem->extension();
                $bgImage = time() . "." . $ext;
                $request->imagem->move($destinationPath, $bgImage);
                $data['imagem'] =$destinationPath.$bgImage;
             }
    
             $data['imagem'] = (isset($data['imagem']) && !empty($data['imagem']) ? $data['imagem'] : $character['imagem']);

             Character::whereId($id)->update($data);

             return redirect()->route('characters.index')->with('warning', 'Personagem editado com sucesso!');
        }


        return redirect()->route('characters.index');
        
    }

    public function destroy($id){

        $character = Character::find($id);

        if($character){
            $character->delete();
            return redirect()->route('characters.index')->with('warning', 'Personagem removido com sucesso!');
        }
            
        return redirect()->route('characters.index');
            
    }

    protected function validator($data){
        return Validator::make($data, [
            'descricao' => ['required', 'string', 'max:255']
        ]);
    }
}

resources/views/admin/characters/create.blade.php
@extends('adminlte::page')
    
@section('title', 'Painel Administrativo')

@section('content_header')
    <h1>Novo Personagem</h1>
@endsection

@section('content')

    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                <h5>Houve um erro ao editar o(s) itens:</h5>
                @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(session('warning'))
        <div class="alert alert-success">
            {{session('warning')}}
        </div>
    @endif


    <div class="card">
        <div class="card-body">
            <form action="{{route('characters.store')}}" method="POST" class="form-horizontal" enctype="multipart/form-data">
                @csrf 

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Imagem</label>
                    <div class="col-sm-10">
                    <input type="file" name="imagem" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Descrição</label>
                    <div class="col-sm-10">
                        <input type="text" name="descricao" placeholder="Informe a descrição do personagem" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input type="submit" value="Salvar" class="btn btn-success" />
                    </div>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/characters/edit.blade.php
@extends('adminlte::page')
    
@section('title', 'Painel Administrativo')

@section('content_header')
    <h1>Atualizar Personagem</h1>
@endsection

@section('content')

    @if($errors->any())
        <div class="alert alert-danger">
            <ul>
                <h5>Houve um erro ao editar o(s) itens:</h5>
                @foreach ($errors->all() as $error)
                    <li>{{$error}}</li>
                @endforeach
            </ul>
        </div>
    @endif

    @if(session('warning'))
        <div class="alert alert-success">
            {{session('warning')}}
        </div>
    @endif


    <div class="card">
        <div class="card-body">
            <form action="{{route('characters.update', ['character' => $character->id])}}" method="POST" class="form-horizontal" enctype="multipart/form-data">
                @method('PUT')
                @csrf 

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Imagem</label>
                    <div class="col-sm-10">
                    <input type="file" name="imagem" class="form-control" />
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Imagem atual:</label>
                    <div class="col-sm-10">
                    <img src="{{URL::to('/').'/'.$character['imagem']}}" class="img-fluid">
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label">Descrição</label>
                    <div class="col-sm-10">
                        <textarea name="descricao" class="form-control">{{$character['descricao']}}</textarea>
                    </div>
                </div>

                <div class="form-group row">
                    <label class="col-sm-2 col-form-label"></label>
                    <div class="col-sm-10">
                        <input type="submit" value="Salvar" class="btn btn-success" />
                    </div>
                </div>

            </form>
        </div>
    </div>

@endsection

resources/views/admin/characters/index.blade.php
@extends('adminlte::page')
    
@section('title', 'Painel Administrativo')

@section('content_header')
    <h1>Personagens</h1>
    <a href="{{ route('characters.create') }}" class="btn btn-sm btn-success">Novo Personagem </a>
@endsection

@section('content')

    @if(session('warning'))
            <div class="alert alert-success">
                {{session('warning')}}
            </div>
    @endif

<div class="card">
    <div class="card-body">
        <table class="table table-hover">
            <thead>
            <tr>
                <th scope="col">#</th>
                <th scope="col">Descrição</th>
                <th scope="col">Ações</th>
            </tr>
            </thead>
            <tbody>
                @foreach ($characters as $character)
                    <tr>
                        <th scope="row">{{$character->id}}</th>
                        <td>{{$character->descricao}}</td>
                        <td>
                            <a href="{{route('characters.edit', ['character' => $character->id])}}" class="btn btn-sm btn-warning">Editar</a>
                            <form action="{{ route('characters.destroy', ['character' => $character->id])}}" method="post">
                                @csrf
                                @method('DELETE')
                                <button class="btn btn-danger" type="submit">Remover</button>
                           </form>
                        </td>
                    </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>


{{$characters->links()}}

@endsection